version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: monthly
    groups:
      github-actions:
        patterns:
          - "*"

  - package-ecosystem: npm
    directory: /
    versioning-strategy: widen
    schedule:
      interval: weekly
    groups:
      development-dependencies:
        dependency-type: "development"
